Get closer to booting a rootfs, IDE is not loading in initramfs though

diff --git a/initramfs/sbin/init b/initramfs/sbin/init
--- a/initramfs/sbin/init
+++ b/initramfs/sbin/init
@@ -19,3 +19,30 @@ mount -t sysfs sysfs /sys
 mount -t devtmpfs devtmpfs /dev
 
 echo "[*] Mounting root filesystem..."
+CMDLINE="$(cat /proc/cmdline)"
+echo "cmdline: $CMDLINE"
+
+ROOTDEV=""
+for arg in $CMDLINE; do
+  case "$arg" in
+    root=*)
+      ROOTDEV="${arg#root=}"
+      ;;
+  esac
+done
+
+echo "root device: $ROOTDEV"
+mkdir -p /newroot
+mount -t ext4 "$ROOTDEV" /newroot
+if [ $? -ne 0 ]; then
+    echo "Error Code: $?" 
+    echo "Failed to mount root device: $ROOTDEV"
+    exit
+fi
+
+echo "[*] Switching to new root..."
+mkdir -p /newroot/proc /newroot/sys /newroot/dev
+mount --move /proc /newroot/proc
+mount --move /sys  /newroot/sys
+mount --move /dev  /newroot/dev
+exec switch_root /newroot /sbin/init
